### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by g00dv1n**
add moon-phase-widget

### CODE REVIEW

**Comment by hodgef** [comment]
Hey @g00dv1n, Thanks sharing such a nice widget! Keep up the great work 🎉

**Comment by g00dv1n** [comment]
> Hey @g00dv1n, Thanks sharing such a nice widget! Keep up the great work

Thanks for a simple template without overhead :+1:

**Comment by hodgef** [comment]
@g00dv1n By the way, I just noticed that some unnecessary files are being pushed to npm, so I just added an `.npmignore` file to the repo. Feel free to add it to your project to reduce the package size at the next publish :)

https://github.com/hodgef/js-library-boilerplate-basic/blob/master/.npmignore

**Comment by g00dv1n** [comment]
> @g00dv1n By the way, I just noticed that some unnecessary files are being pushed to npm, so I just added an `.npmignore` file to the repo. Feel free to add it to your project to reduce the package size at the next publish :)
> 
> https://github.com/hodgef/js-library-boilerplate-basic/blob/master/.npmignore

Cool. Thanks. Will add to my repo too

**Pull request merged**
